### ISSUE TITLE
Почему 😡

### ISSUE THREAD

**Issue by FunnyRain** [Bestaford/PMMP-VK-RCON-bot#1]
Почему не моя библиотека 😡 а дурацкая симплевк для нубов . Очень разочарован!!!

**Comment by Bestaford** [comment]
Tak slozhilos`

**Comment by FunnyRain** [comment]
Kozel

**Comment by Bestaford** [comment]
A pochemu ya dolzhen bil ispolzovat` ne simplevk, esli eto vpolne norm liba

**Comment by FunnyRain** [comment]
Моя библиотека лучше!!!!!! Симплевк гавно

**Comment by Bestaford** [comment]
А пруфы

**Comment by FunnyRain** [comment]
У меня быстрее чем у симплевк и лучше!

**Comment by Bestaford** [comment]
У simplevk не наблюдается проблем со скоростью

**Comment by FunnyRain** [comment]
Нет наблюдается! Я вижу а у меня не наблюдается

**Comment by iteplenky** [comment]
ребят я пользуюсь бесплатным конструктором ботов и все просто летает

**Comment by FunnyRain** [comment]
@iteplenky ты нуб

**Comment by Bestaford** [comment]
@iteplenky конструктор сайтов

**Comment by Bestaford** [comment]
ишшу закрыт по причине фанни рейн дурачок

**Comment by FunnyRain** [comment]
Пруфы жду в лс vk com/offnikgay
